<?php

namespace DiscordBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Method for login
     */
    public function verifUserPass($username, $password)
    {
        return $this->createQueryBuilder('user')
            ->where("user.name == $username")
            ->andWhere("user.password == $password")
            ->getQuery()
            ->getResult();
    }

}
