<?php

namespace DiscordBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function verifUserLogs($username, $password)
    {
        return $this->createQueryBuilder('user')
            ->where('user.name = :name')
            ->andWhere('user.password = :pwd')
            ->setParameter('name', $username)
            ->setParameter('pwd', $password);
    }

}
